baseURL = "https://gohugo.io"
title = "Timo Sarkar"
author = "Timo Sarkar"
copyright = "Copyright © 2019 - 2023 Timo Sarkar"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
theme = "blank"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.home]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10  

  [[menu.curiculum]]
    identifier = "curiculum"
    name = "CV"
    url = "/curiculum/"
    weight = 10

  [[menu.tribute]]
    identifier = "tribute"
    name = "Tribute"
    url = "/tribute/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
